---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 27017, host: 27017}]
  - ["forwarded_port", {guest: 9200, host: 9200}]
  - ["forwarded_port", {guest: 9300, host: 9300}]
  synced_folders:
  - ["./src/test/resources", "/home/vagrant/synced_folders/src/test/resources"]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
    - apt
    - mongodb
    - java
    - elasticsearch
    - elasticsearch::plugins
    attributes:
      java:
        #install_flavor: "oracle"
        jdk_version: 7
        #oracle:
         #accept_oracle_download_terms: true
      ssl:
        verify: false
      mongodb:
        cluster_name: "gazetteer-dev"
        config:
          replSet: "rs0"
      elasticsearch:
        cluster:
          name: "gazetteer.dainst.org"
        version: "1.3.4"
        plugins:
          elasticsearch/elasticsearch-analysis-icu: { version: 2.0.0 }
          com.github.richardwilly98.elasticsearch/elasticsearch-river-mongodb: { version: 2.0.1 }
